export const textCardInfo = [
  {
    userIdx: 1,
    postIdx: 1,
    findIdx: 8,
    title: "이름",
    secondaryText: "추가정보",
    date: new Date(2022, 6, 24),
    scrap: false,
    imgsrc: "/testImg/image3.jpeg",
  },
  {
    userIdx: 3,
    postIdx: 2,
    findIdx: 2,
    title: "만수",
    secondaryText: "추가정보2",
    date: new Date(2022, 0, 24),
    scrap: true,
    imgsrc: "/testImg/image2.jpeg",
  },
  {
    userIdx: 4,
    postIdx: 3,
    findIdx: 3,
    title: "무강",
    secondaryText: "추가정보3",
    date: new Date(2022, 11, 24),
    scrap: true,
    imgsrc: "/testImg/image1.jpeg",
  },
  {
    userIdx: 6,
    postIdx: 4,
    findIdx: 10,
    title: "달덩이",
    secondaryText: "추가정보4",
    date: new Date(2022, 7, 1),
    scrap: false,
    imgsrc: "/testImg/image2.jpeg",
  },
  {
    userIdx: 5,
    postIdx: 5,
    findIdx: 5,
    title: "대롱이",
    secondaryText: "추가정보5",
    date: new Date(2022, 7, 21),
    scrap: false,
    imgsrc: "/testImg/image1.jpeg",
  },
];
